### ISSUE TITLE
Bubbling up the status and error messages from Armada to workflow level at airshipctl

### ISSUE THREAD

**Issue by singhannie** [airshipit/airshipctl#97]
**Problem description (if applicable)**
When software components for platform services are deployed by Helm charts via Argo workflows, It is likely that chart deployment may fail, subsequently leading to failure of workflow. It is imperative that status of workflows and details of any failures/errors at any level shall be made available to the end user, operating airshipctl, to get a bird-eye view.

**Proposed change**

- The results from Armada-cli about chart deployment and status messages for errors required to be bubbled up to workflow level to get the bird-eye view of the state and status of workflow.
    - Airshipctl shall support pulling the logs of "sitemanage" workflow or any lower level workflows
    - Airshipctl shall support getting the status of workflows.
- When a chart deployment / upgrade (function level workflow) fails
    - if the failed chart is a protected chart, Argo workflow shall honor "continue_processing" flag based on that it should stop or continue the workflow execution.
    - Functionality of protected chart should be supported as is in Airship 1.0.

**Potential impacts**
It would enable end user to get status and error messages right at the entry point of airshipctl and know the details problem to identify corrective action, if required.

**Comment by seaneagan** [comment]
Do we need CLI or just GUI?

# GUI options
* prometheus/grafana?
* argo ui (via airship ui)?

# CLI options
* argo CLI shows success/failure of each task, doesn't show finer level details of whether install/upgrade/test was performed for example, which is available in logs, but...
* do we plan to install an [argo artifact repository](https://github.com/argoproj/argo/blob/master/docs/configure-artifact-repository.md#configuring-your-artifact-repository)?
* is there a general plan for how to utilize CLIs of dependencies e.g. `argo`, `kubectl`, `kustomize`, `helm`? for example logs and overall workflow status can be retrieved from `argo`.

there will be no specific work required to support protected chart handling, that continues to just be a field in the armada chart document, so maybe we can remove that from here.

**Comment by seaneagan** [comment]
# Design Proposal

* Prometheus/Grafana seems like the most robust/flexible/consistent/future-proof option.
* Builds on the metric data already supported by Armada.
* Just need to deploy Prometheus as the first Chart in order to capture data for all Charts, even Prometheus itself, as the metrics wouldn't be collected until after the Argo task is completed at which point Prometheus will already be up and collecting data.

# Tasks

- [ ] Add Armada support for json metric output: `armada apply_chart --metrics-output <path> --metrics-output-format json ...` which exposes each chart level [metric and label info](https://airshipit.readthedocs.io/projects/armada/en/latest/operations/metrics.html)
- [ ] Add [output parameters](https://argoproj.github.io/docs/argo/examples/readme.html#output-parameters) to the Armada apply chart WorkflowTemplate and python script which consumes `--metrics-output-format json` to store each metric in it's own output parameter file path
- [ ] Add [metrics key](https://github.com/argoproj/argo/blob/master/docs/metrics.md) to the Armada apply chart WorkflowTemplate which defines metrics for all of the output parameters
- [ ] Create Grafana Dashboard to consume these metrics
